### DISCUSSION TITLE
OpenAPI Integration

### DISCUSSION THREAD

**Discussion by wiverson** [supabase-community/supabase-csharp#75] [Ideas]
As an experiment, I decided to try using the [OpenAPI csharp generator](https://openapi-generator.tech/docs/generators/csharp-netcore) with PostgREST. Here's the [PostgREST info on OpenAPI](https://postgrest.org/en/stable/references/api/openapi.html) support.

I was pretty impressed with my initial experiment. I was able to fetch the OpenAPI configuration details from my project with the following:

```
https://PROJECT-ID.supabase.co/rest/v1/?apikey=APIKEY
``` 

I saved that JSON file to a directory as api.json.

I installed the [OpenAPI generator tool via brew](https://openapi-generator.tech/docs/installation).

I then used  this config file as config.yaml:

```yaml
outputDir: out/csharp-netcore
generatorName: csharp-netcore
apiPackage: io.dayboard.api
packageName: io.dayboard.rpc
inputSpec: api.json
additionalProperties:
  packageGuid: "{321C8C3F-0156-40C1-AE42-D59761FB9B6C}"
  '!include': 'shared/nested.yaml'
  targetFramework: netstandard2.0
```

Running `openapi-generator batch config.yaml` then produced quite a few files that matched up to the APIs I've been generating, including everything from the client code, models, and what looks like test cases.

It looks like the generator is using Mustache for templating, and it's using [RestSharp](https://github.com/restsharp/RestSharp) to build the client.

Any thoughts on using any of this stuff with Supabase? Either generating/customizing the generated output, and/or using it in addition to or instead of the supabase-postgrest client...?

**Comment by acupofjose** [comment]
Very interesting indeed! Worked for me to get a client generated and, you're right, it gives a pretty impressive set of generated classes. I wonder if it could be used just to generate models. That's one of the main drawbacks on getting people onboarded to postgrest-csharp I think - there is too much time spent manually parsing through models and defining key/value relationships. 

To me, it seems like this would be most useful as a separate cli app that would leverage the `swagger.json` produced by `PostgREST` and generate the appropriate c# `BaseModel` classes.

**Reply by wiverson** [reply]
Yeah, I think a companion cli tool probably would be best.

One option might be to just document how to use the generator tooling with Supabase. As far as I can tell, it looks like just figure out how to add the apiKey and session stuff to the headers and one would basically be off to the races?

FWIW Unity now supports [.NET Standard 2.1](https://docs.unity3d.com/2023.2/Documentation/Manual/dotnetProfileSupport.html), which could mean a pretty thin dependency graph.

I think the steps would be basically documenting:

1. Run a curl or Windows equivalent to download the OpenAPI config
2. Install/run the OpenAPI tooling pointed at that
3. Run the tools with a recommended configuration
4. Add a simple wrapper/config to use with supabase-csharp to grab/config the apiKey & session (basically just GetHeaders?) 
5. Drop the results into a project

Of course I already have ~50 calls all wrapping/parsing JSON responses from my existing RPC but would be nice to not have to maintain it.

**Reply by wiverson** [reply]
FWIW writing a Supabase specific generator looks like a fun project but that could easily take weeks given all the permutations. Hmm.

**Reply by wiverson** [reply]
Hmm. I got what looked like a reasonable build in out with this config:

```yaml
outputDir: out/csharp-netcore
generatorName: csharp-netcore
packageName: io.dayboard.server
apiNameSuffix: "Request"
modelNamePrefix: ""
modelNameSuffix: "Model"
inputSpec: api.json
additionalProperties:
  '!include': 'shared/nested.yaml'
  packageGuid: "{321C8C3F-0156-40C1-AE42-D59761FB9B6C}"
  targetFramework: netstandard2.1
  apiName: "Application"
  hideGenerationTimestamp: true
```

But I'm not seeing the response objects. It looks like the PostgREST Swagger JSON isn't including response type structure, so the JSON and the generated code are treating everything as just returning 200/OK is all they do, no response models.

Very close. Would be a fun project to work on but I suspect this is more of a Supabase has to throw some $ at it kind of situation. I'm not seeing response type info in the autogenerated API docs for the functions either in the Supabase dashboard. TBH I'm not sure if it would be easier to try to get all of this sorted out via OpenAPI or if it would be easier to just write a generator that inspected the public functions directly.
